import { describe, it, expect } from 'vitest';
import { NodeMetadataKey, decryptMetadataBundle } from './metadata';

const encoder = new TextEncoder();

function keyHex(key: NodeMetadataKey): string {
  return Array.from(key.asBytes())
    .map(b => b.toString(16).padStart(2, '0'))
    .join('');
}

// Vectors generated by core/src/metadata_crypto.rs (NodeMetadataKey::derive +
// encrypt) — lock cross-implementation compatibility with the Rust client.
const RUST_IKM = encoder.encode('accord-test-identity-key-material');
const RUST_NODE_ID = 'c0ffee00-1234-5678-9abc-def012345678';
const RUST_KEY_HEX = '5da864d1749010774d971235b7ae530a60606638301bec301e7162afdd95c0f6';
const RUST_BLOB_B64 = 'ATjWbT0VA5j9oZhB8sF7sE+aW/Nzg+0BKJefMbZuSwDlK/7Mgjiwg9v6hqQVRJbKuUA=';
const RUST_BLOB_PLAINTEXT = 'Accord Test Node 🔐';
const RUST_META_NAME_B64 = 'AfLeIGVkIIIXqwTjGQQ+NKGRPzPnApQORTW1H8wymsiLWDEa';
const RUST_META_DESC_B64 = 'AdRy1EF7DipjaiMkwd5WQLp7jTU9i/c/ewtJeYhvOXwDHgtEYyskEVX1Nvft';

describe('NodeMetadataKey', () => {
  it('derives the same key as the Rust implementation', () => {
    const key = NodeMetadataKey.derive(RUST_IKM, RUST_NODE_ID);
    expect(keyHex(key)).toBe(RUST_KEY_HEX);
  });

  it('decrypts a blob produced by the Rust implementation', () => {
    const key = NodeMetadataKey.derive(RUST_IKM, RUST_NODE_ID);
    expect(key.decryptFromBase64(RUST_BLOB_B64)).toBe(RUST_BLOB_PLAINTEXT);
  });

  it('decrypts a Rust EncryptedMetadata bundle', () => {
    const key = NodeMetadataKey.derive(RUST_IKM, RUST_NODE_ID);
    expect(key.decryptFromBase64(RUST_META_NAME_B64)).toBe('General');
    expect(key.decryptFromBase64(RUST_META_DESC_B64)).toBe('The main channel');
  });

  it('derivation is deterministic and node-scoped', () => {
    const a1 = NodeMetadataKey.derive(RUST_IKM, 'node-a');
    const a2 = NodeMetadataKey.derive(RUST_IKM, 'node-a');
    const b = NodeMetadataKey.derive(RUST_IKM, 'node-b');
    expect(keyHex(a1)).toBe(keyHex(a2));
    expect(keyHex(a1)).not.toBe(keyHex(b));
  });

  it('encrypt/decrypt roundtrip with unicode', () => {
    const key = NodeMetadataKey.derive(RUST_IKM, 'node');
    const plaintext = '🔒 Ünïcödé Nödé 日本語';
    expect(key.decrypt(key.encrypt(plaintext))).toBe(plaintext);
    expect(key.decryptFromBase64(key.encryptToBase64(plaintext))).toBe(plaintext);
  });

  it('same plaintext encrypts to different blobs (random nonce)', () => {
    const key = NodeMetadataKey.derive(RUST_IKM, 'node');
    expect(key.encryptToBase64('same')).not.toBe(key.encryptToBase64('same'));
  });

  it('wrong key fails to decrypt', () => {
    const k1 = NodeMetadataKey.derive(RUST_IKM, 'node-1');
    const k2 = NodeMetadataKey.derive(RUST_IKM, 'node-2');
    const blob = k1.encrypt('secret');
    expect(() => k2.decrypt(blob)).toThrow();
  });

  it('tampered blob fails to decrypt', () => {
    const key = NodeMetadataKey.derive(RUST_IKM, 'node');
    const blob = key.encrypt('secret');
    blob[blob.length - 1] ^= 0xff;
    expect(() => key.decrypt(blob)).toThrow();
  });

  it('rejects empty, short, and wrong-version blobs', () => {
    const key = NodeMetadataKey.derive(RUST_IKM, 'node');
    expect(() => key.decrypt(new Uint8Array(0))).toThrow(/empty/);
    expect(() => key.decrypt(new Uint8Array([1, 2, 3]))).toThrow(/too short/);
    const blob = key.encrypt('x');
    blob[0] = 99;
    expect(() => key.decrypt(blob)).toThrow(/version/);
  });

  it('fromBytes/asBytes roundtrip preserves the key', () => {
    const key = NodeMetadataKey.derive(RUST_IKM, 'node');
    const clone = NodeMetadataKey.fromBytes(key.asBytes());
    expect(clone.decrypt(key.encrypt('shared'))).toBe('shared');
  });
});

describe('decryptMetadataBundle', () => {
  it('decrypts all fields and skips undecryptable entries', () => {
    const key = NodeMetadataKey.derive(RUST_IKM, 'node');
    const wrongKey = NodeMetadataKey.derive(RUST_IKM, 'other-node');

    const result = decryptMetadataBundle(
      {
        node: {
          encrypted_name: key.encryptToBase64('My Node'),
          encrypted_description: key.encryptToBase64('About us'),
        },
        channels: {
          'chan-1': key.encryptToBase64('general'),
          'chan-2': wrongKey.encryptToBase64('unreadable'),
        },
        categories: {
          'cat-1': key.encryptToBase64('Text Channels'),
        },
      },
      key,
    );

    expect(result.nodeName).toBe('My Node');
    expect(result.nodeDescription).toBe('About us');
    expect(result.channelNames.get('chan-1')).toBe('general');
    expect(result.channelNames.has('chan-2')).toBe(false);
    expect(result.categoryNames.get('cat-1')).toBe('Text Channels');
  });

  it('handles an empty bundle', () => {
    const key = NodeMetadataKey.derive(RUST_IKM, 'node');
    const result = decryptMetadataBundle({ node: {}, channels: {}, categories: {} }, key);
    expect(result.nodeName).toBeUndefined();
    expect(result.nodeDescription).toBeUndefined();
    expect(result.channelNames.size).toBe(0);
    expect(result.categoryNames.size).toBe(0);
  });
});
